Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/supplychain.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.supplychain.com:7050
      - orderer2.supplychain.com:8050
      - orderer3.supplychain.com:9050

  - &DuyMinhOrg
      Name: DuyMinhOrgMSP
      ID: DuyMinhOrgMSP
      MSPDir: ../organizations/peerOrganizations/DuyMinhOrg.supplychain.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('DuyMinhOrgMSP.admin', 'DuyMinhOrgMSP.peer', 'DuyMinhOrgMSP.client')"
        Writers:
          Type: Signature
          Rule: "OR('DuyMinhOrgMSP.admin', 'DuyMinhOrgMSP.client')"
        Admins:
          Type: Signature
          Rule: "OR('DuyMinhOrgMSP.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('DuyMinhOrgMSP.peer')"
      AnchorPeers:
        - Host: peer0.DuyMinhOrg.supplychain.com
          Port: 7051
      
  

  

 

 
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.supplychain.com:7050
    - orderer2.supplychain.com:8050
    - orderer3.supplychain.com:9050
  EtcdRaft:
    Consenters:
    - Host: orderer.supplychain.com
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/server.crt
    - Host: orderer2.supplychain.com
      Port: 8050
      ClientTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer2.supplychain.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer2.supplychain.com/tls/server.crt
    - Host: orderer3.supplychain.com
      Port: 9050
      ClientTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer3.supplychain.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer3.supplychain.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB 
    PreferredMaxBytes: 512 KB
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  FourOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults

      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SupplychainConsortium:
        Organizations:
          - *DuyMinhOrg
  
  FourOrgsChannel:
    Consortium: SupplychainConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *DuyMinhOrg
      Capabilities:
        <<: *ApplicationCapabilities